from pathlib import Path
n = "n" + "pm"
BT = chr(96)
parts = []

lines = []
A = lines.append
A('# EQ Legends BiS + Build Simulator')
A('')
A('Local app for Josh Monroe. Pick 1-3 of 16 classes, Priority / Max All BiS, single worn-haste warning, race+slot simulator, XLSX export.')
A('')
A('Decoded item stats come from /workspace/eq-legends/decoded (never invented).')
A('')
A('## Dev start (Linux box)')
A('')
A(BT*3 + 'bash')
A('cd /workspace/eq-legends-app')
A('./start.sh')
A(BT*3)
A('')
A('Or separately:')
A('')
A(BT*3 + 'bash')
A('# API')
A('.venv/bin/uvicorn backend.app.main:app --host 127.0.0.1 --port 8000 --reload')
A('# UI')
A('cd frontend && ' + n + ' install && ' + n + ' run dev')
A(BT*3)
A('')
A('Open UI at http://127.0.0.1:5173 (proxies /api to :8000).')
A('')
A('## Excel')
A('')
A('- scripts/export_xlsx.py')
A('- scripts/run_planner_export.py')
A('- POST /api/export/xlsx')
A('')
A('## Paths')
A('')
A('- decoded: /workspace/eq-legends/decoded (also data/decoded symlink)')
A('- vendored planner modules: backend/vendor/')
A('- xlsx: /workspace/eq-legends/EQ_Legends_BiS.xlsx (packaged app writes under Documents/EQLegendsBiS)')
A('')
A('See STATUS.md')
A('')
A('---')
A('')
A('## Windows .exe (share with brother)')
A('')
A('Packaging uses **Electron + electron-builder** (NSIS installer + portable) with a **FastAPI sidecar** (PyInstaller) and bundled decoded JSON + React production build.')
A('')
A('### What your brother double-clicks')
A('')
A('1. **Portable:** EQ-Legends-BiS-*-portable.exe — no install, double-click to run.')
A('2. **Installer (NSIS):** EQ-Legends-BiS-*-win-x64.exe — Start Menu + desktop shortcut "EQ Legends BiS".')
A('')
A('On launch the app starts the local API (if needed), opens the UI window, and stops the API on quit.')
A('')
A('### Build on Josh\'s Windows PC (recommended)')
A('')
A('Cross-compiling a real Windows .exe + Python sidecar from Linux usually needs Wine/Windows tooling. Build on Windows:')
A('')
A(BT*3 + 'powershell')
A('cd eq-legends-app')
A('')
A('# 1) Node deps for Electron shell')
A(n + ' install')
A('')
A('# 2) Build PyInstaller API sidecar into resources/api/')
A('.\scripts\build_api_sidecar.ps1')
A('')
A('# 3) Bundle decoded JSON + production UI + vendor modules, then package')
A(n + ' run dist:win')
A(BT*3)
A('')
A('Artifacts land in dist-electron/:')
A('')
A('- EQ-Legends-BiS-<ver>-portable.exe')
A('- EQ-Legends-BiS-<ver>-win-x64.exe (NSIS)')
A('')
A('Zip one of those and send to your brother.')
A('')
A('### Build helpers (any OS)')
A('')
A(BT*3 + 'bash')
A(n + ' run prepare:resources   # sync decoded data, build UI into resources/')
A(n + ' run dist:win:dir        # unpackaged win dir (needs Wine on Linux)')
A(n + ' run dist:linux:dir      # Linux unpackaged smoke dir')
A(n + ' run pack:smoke          # current-platform dir build')
A(BT*3)
A('')
A('### Linux box notes')
A('')
A('This environment can prepare resources and attempt electron-builder --win, but producing a runnable Windows installer + eq-api.exe typically requires a Windows machine (or Wine). If cross-compile fails here, the project is still fully wired — use the Windows steps above.')
A('')
A('### How to enable updates')
A('')
A('electron-updater is wired behind env/config. Until a GitHub release repo exists, check-for-updates (IPC eq:check-updates) returns a stub message.')
A('')
A('To enable:')
A('')
A('1. Create a GitHub repo for releases (private is fine with a token for publish).')
A('2. Set when packaging / at runtime:')
A('   - EQ_UPDATE_OWNER = GitHub user/org')
A('   - EQ_UPDATE_REPO = repo name')
A('   - or EQ_UPDATE_URL = generic feed URL (static HTTPS hosting of latest.yml + artifacts)')
A('3. Publish with electron-builder (--publish always) so latest.yml + NSIS/portable land on the feed.')
A('4. Rebuild so the app has the same version in package.json.')
A('')
A('Without those env vars, the app runs offline and never auto-downloads.')
A('')
A('### Share checklist')
A('')
A('- [ ] Build sidecar +  on Windows')
A('- [ ] Smoke-test BiS (1-3 classes), Priority/Max All, haste warn, simulator, XLSX')
A('- [ ] Send portable .exe or NSIS installer to brother')
A('- [ ] Optional: configure update owner/repo and publish a GitHub Release')
A('')
Path('/workspace/eq-legends-app/README.md').write_text('\n'.join(lines) + '\n')
print('wrote README', len(lines))
